---
name: Terragrunt apply on comment
on:
  issue_comment:
    types: [created]

jobs:
  terragrunt-apply:
    uses: northvolt/shared-workflows/.github/workflows/terragrunt-apply-azure-oidc.yml@TOC-2257
    with:
      plan_workflow: plan.yml
    secrets:
      ssh_key: ${{ secrets.NV_CI_SSH_KEY }}
      arm_client_id: ${{ secrets.arm_client_id }}
      arm_tenant_id: ${{ secrets.arm_tenant_id }}

