name: Generate terraform docs
on:
  - pull_request

jobs:
  terraform-doc:
    uses: northvolt/shared-workflows/.github/workflows/terragrunt-fmt.yml@v1
    secrets:
      actions_gpg_private_key: ${{ secrets.ACTIONS_GPG_PRIVATE_KEY }}
      actions_gpg_passphrase: ${{ secrets.ACTIONS_GPG_PASSPHRASE }}
