---
name: Update README.md for project changes

on:
  workflow_call:
    inputs:
      terragrunt_version:
        required: false
        default: "0.47.0"
        type: string
      terraform_version:
        required: false
        default: "1.5.0"
        type: string
      python_version:
        required: false
        default: "3.10"
        type: string
      jira_url:
        required: false
        default: "https://northvolt.atlassian.net/browse"
        type: string
      azure_portal_url:
        required: false
        default: "https://portal.azure.com/#@northvolt.com"
        type: string
      default_branch:
        required: false
        default: "master"
        type: string
    secrets:
      actions_gpg_private_key:
        description: 'GPG key to sign commits'
        required: true
      actions_gpg_passphrase:
        description: 'Passphrase for the GPG key'
        required: true

jobs:
  update_projects_readme:
    runs-on: ubuntu-22.04
    steps:
      - name: Check project.hcl changed
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            project:
              - "**/project.hcl"

      - name: Checkout code
        if: steps.changes.outputs.project == 'true'
        uses: actions/checkout@v3.5.2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Terragrunt
        if: steps.changes.outputs.project == 'true'
        uses: autero1/action-terragrunt@v1.3.0
        with:
          terragrunt_version: ${{ inputs.terragrunt_version }}

      - name: Setup Terraform
        if: steps.changes.outputs.project == 'true'
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ${{ inputs.terraform_version }}
          terraform_wrapper: false

      - name: Setup python
        if: steps.changes.outputs.project == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
          cache: 'pip'

      - name: Install dependencies
        if: steps.changes.outputs.project == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt

      - name: Checkout README.md and PROJECTS.md from main branch
        if: steps.changes.outputs.project == 'true'
        run: |
          git fetch origin ${{ inputs.default_branch }}
          git restore -s origin/${{ inputs.default_branch }} README.md
          git restore -s origin/${{ inputs.default_branch }} PROJECTS.md

      - name: Execute README.md update script
        if: steps.changes.outputs.project == 'true'
        run: python .github/workflows/readme_projects.py
        env:
          ROOT_DIR: ${{ github.workspace }}
          JIRA_URL: ${{ inputs.jira_url }}
          AZURE_PORTAL_URL: ${{ inputs.azure_portal_url }}

      - name: Import bot's GPG key for signing commits
        if: steps.changes.outputs.project == 'true'
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@6f6401f19d4d5866d07e9026b6468c69596e9470
        with:
          gpg_private_key: ${{ secrets.actions_gpg_private_key }}
          passphrase: ${{ secrets.actions_gpg_passphrase }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Add and commit fmt changes
        if: steps.changes.outputs.project == 'true'
        uses: EndBug/add-and-commit@fc734f817560acc116627c6133815f6289cd96ce
        with:
          add: README.md PROJECTS.md
          message: 'Update README.md and PROJECTS.md file with new projects'
          author_name: ${{ steps.import-gpg.outputs.name }}
          author_email: ${{ steps.import-gpg.outputs.email }}
          push: true
