---
name: Update confluence for project changes

on:
  workflow_call:
    inputs:
      terragrunt_version:
        required: false
        default: "0.47.0"
        type: string
      terraform_version:
        required: false
        default: "1.5.0"
        type: string
      python_version:
        required: false
        default: "3.10"
        type: string
      jira_url:
        required: false
        default: "https://northvolt.atlassian.net/browse"
        type: string
      azure_portal_url:
        required: false
        default: "https://portal.azure.com/#@northvolt.com"
        type: string
      default_branch:
        required: false
        default: "master"
        type: string
    secrets:
      actions_confluence_api_token:
        description: 'API token for Confluence'
        required: true

jobs:
  update_projects_readme:
    runs-on: ubuntu-22.04
    steps:
      - name: Check project.hcl changed
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            project:
              - "**/project.hcl"
          list-files: 'shell'

      - name: Checkout code
        if: steps.changes.outputs.project == 'true'
        uses: actions/checkout@v3.5.2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Check for tags in project.hcl
        id: check_project_tags
        if: steps.changes.outputs.project == 'true'
        run: |
          CHANGED_FILES=("${{ steps.changes.outputs.project_files }}")
          if echo $CHANGED_FILES | grep -q 'project.hcl'; then
            if grep -q -E 'project|infrastructure-owner' $CHANGED_FILES; then
              echo "tags_present=true" >> $GITHUB_OUTPUT
            else
              echo "tags_present=false" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Set variable for continuing workflow or not
        id: project_tags_present
        if: steps.changes.outputs.project == 'true' && steps.check_project_tags.outputs.tags_present == 'true'
        run: echo "continue=true" >> $GITHUB_OUTPUT

      - name: Setup Terragrunt
        if: steps.project_tags_present.outputs.continue == 'true'
        uses: autero1/action-terragrunt@v1.3.0
        with:
          terragrunt_version: ${{ inputs.terragrunt_version }}

      - name: Setup Terraform
        if: steps.project_tags_present.outputs.continue == 'true'
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ${{ inputs.terraform_version }}
          terraform_wrapper: false

      - name: Setup python
        if: steps.project_tags_present.outputs.continue == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
          cache: 'pip'

      - name: Install dependencies
        if: steps.project_tags_present.outputs.continue == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt

      - name: Execute Confluence projects update script
        if: steps.project_tags_present.outputs.continue == 'true'
        run: python .github/workflows/confluence_projects.py
        env:
          ROOT_DIR: ${{ github.workspace }}
          JIRA_URL: ${{ inputs.jira_url }}
          AZURE_PORTAL_URL: ${{ inputs.azure_portal_url }}
          CONFLUENCE_API_TOKEN: ${{ secrets.actions_confluence_api_token }}

